// DSR template items — from official Design Safety Review Checklist
// Shared between dsr.ts route and auto-creation in moc.ts / review.ts
export const DSR_TEMPLATE_ITEMS: { category: string; description: string }[] = [
  { category: 'administration', description: 'Based on the current design, is the proposed change consistent with the original Process Hazard Analysis (PHA) assessment?' },
  { category: 'administration', description: 'Does the design comply with ISP Standards?' },
  { category: 'administration', description: 'Has the impact of the change on existing buildings been considered?' },
  { category: 'administration', description: 'Has any impact, beyond unit boundaries, associated with this change been properly dealt with and/or communicated?' },
  { category: 'administration', description: 'Have exposures to existing buildings been considered when siting new vessels, utilities, temporary/permanent buildings or sheds, etc.?' },
  { category: 'administration', description: 'Have noncombustible materials or construction been used?' },
  { category: 'material_safety_regulatory', description: 'Have TSCA change scenarios been considered for applicability?' },
  { category: 'material_safety_regulatory', description: 'Have MSDS or Preliminary Product Safety Data Sheets been obtained for all chemicals to be handled?' },
  { category: 'material_safety_regulatory', description: 'Has the potential for a hazardous chemical reaction in sumps and sewers been considered?' },
  { category: 'material_safety_regulatory', description: 'Have all other potential product regulatory issues been addressed (DOT, FIFRA, BATF, FDA, ISO 9001)?' },
  { category: 'pressure_vacuum_relief', description: 'Have new or modified safety relief devices or vent systems been designed in accordance with requirements?' },
  { category: 'pressure_vacuum_relief', description: 'Has potential for external pressure (vacuum) from sudden cooling, condensing, pump-out, etc. been addressed?' },
  { category: 'pressure_vacuum_relief', description: 'Have only full-port valves been specified for use at inlet and outlet of pressure/vacuum relief devices?' },
  { category: 'pressure_vacuum_relief', description: 'Have any changes to safety relief device inlet or outlet piping been properly reviewed?' },
  { category: 'pressure_vacuum_relief', description: 'Will adequate facilities (alarms, detectors, redundancy) be provided to minimize risk of relief device actuating?' },
  { category: 'pressure_vacuum_relief', description: 'Have the discharges of safety relief devices been located to avoid potential personnel injury?' },
  { category: 'pressure_vacuum_relief', description: 'Has the design included installation of the safety relief valve vertically?' },
  { category: 'temperature_reaction', description: 'Has potential for formation of unwanted by-products been adequately addressed?' },
  { category: 'temperature_reaction', description: 'Has potential for loss of flow or reverse flow been adequately addressed?' },
  { category: 'temperature_reaction', description: 'Have adequate provisions been made so that normally dilute but reactive materials cannot be concentrated/accumulated in unexpected areas?' },
  { category: 'temperature_reaction', description: 'Is adequate freeze protection provided?' },
  { category: 'valves_and_piping', description: 'Have the proper Valve and Piping specifications been used?' },
  { category: 'valves_and_piping', description: 'Have cross-tied lines been reviewed to minimize contamination potential and eliminate mixing of reactive chemicals?' },
  { category: 'valves_and_piping', description: 'Have test methods and documentation requirements been specified to ensure integrity of piping systems?' },
  { category: 'valves_and_piping', description: 'Will sample points be properly configured for safe sampling of hazardous chemicals?' },
  { category: 'valves_and_piping', description: 'Have all open ended valves and hand-operated ball valves been designed per environmental requirements?' },
  { category: 'valves_and_piping', description: 'Have hot-taps been reviewed and eliminated where possible?' },
  { category: 'valves_and_piping', description: 'Will necessary excess flow and back-flow prevention measures be provided?' },
  { category: 'valves_and_piping', description: 'Has line expansion and vibration during startup, shutdown, cleaning, etc. been considered?' },
  { category: 'valves_and_piping', description: 'Has the potential risk and consequences of hydraulic hammering been considered?' },
  { category: 'valves_and_piping', description: 'Have appropriate materials of construction been considered for compatibility, corrosion resistance and GMP requirements?' },
  { category: 'valves_and_piping', description: 'Have temporary start-up strainers been identified to ensure removal for normal operation?' },
  { category: 'valves_and_piping', description: 'Has the design included the proper encasing of underground piping at stress points?' },
  { category: 'rotating_mechanical_equipment', description: 'Have special precautions for safe operation of equipment been considered (reverse flow, minimum flow, etc.)?' },
  { category: 'rotating_mechanical_equipment', description: 'Do new and revised pumps and/or pump seals meet GMP requirements and ISP standards?' },
  { category: 'rotating_mechanical_equipment', description: 'Have lubricants and buffer fluids been properly selected to meet any GMP requirements?' },
  { category: 'rotating_mechanical_equipment', description: 'Will moving parts on machinery be properly guarded?' },
  { category: 'rotating_mechanical_equipment', description: 'Will pumps be located in accordance with ISP Standards?' },
  { category: 'rotating_mechanical_equipment', description: 'Are the emergency shutdown systems adequate (overspeed, ground fault, high temperature, vibration, etc.)?' },
  { category: 'rotating_mechanical_equipment', description: 'Have appropriate materials of construction been considered for compatibility, corrosion resistance and GMP requirements?' },
  { category: 'rotating_mechanical_equipment', description: 'Will adequate pressure relief be provided for new or modified pump systems?' },
  { category: 'instrumentation', description: 'Has the potential for instrument failure been adequately addressed?' },
  { category: 'instrumentation', description: 'Have all new shutdown devices been designed to permit testing?' },
  { category: 'instrumentation', description: 'Have potential consequences of instrument or computer failure been considered (redundancy, backup power, etc.)?' },
  { category: 'instrumentation', description: 'Has control valve fail-safe position on loss of electric power or air/nitrogen been properly specified?' },
  { category: 'instrumentation', description: 'Have provisions been made to safeguard against risks of control valves going full open or closed?' },
  { category: 'instrumentation', description: 'If the change affects a shutdown or ESD system, have issues been addressed?' },
  { category: 'instrumentation', description: 'Will alarms associated with critical instruments be clearly displayed in the control room?' },
  { category: 'instrumentation', description: 'Have any special concerns with response time or sequencing been adequately addressed?' },
  { category: 'instrumentation', description: 'Have process changes been considered in the design of new and existing instrumentation?' },
  { category: 'instrumentation', description: 'Has ESD control logic been reviewed?' },
  { category: 'instrumentation', description: 'Will temperature elements be mounted in thermo wells?' },
  { category: 'instrumentation', description: 'Have appropriate materials of construction been considered for compatibility and GMP requirements?' },
  { category: 'instrumentation', description: 'Has adequate local instrumentation been addressed for safety and trouble-shooting purposes?' },
  { category: 'instrumentation', description: 'Is the location of sensing elements proper to ensure correct measurement?' },
  { category: 'electrical_systems', description: 'Have instrumentation and electrical equipment enclosures been specified to meet the electrical classification of the area?' },
  { category: 'electrical_systems', description: 'Have wire gauges, starters and overloads been properly sized per the National Electric Code?' },
  { category: 'electrical_systems', description: 'Has the design considered requirements of Electrical Hot Work and Cranes Near Power Lines?' },
  { category: 'electrical_systems', description: 'Has the design included adequate room for ventilation of transformers, motors, etc.?' },
  { category: 'fire_protection', description: 'Has the potential for static electricity buildup been adequately addressed?' },
  { category: 'fire_protection', description: 'Has proper grounding of all electrical and process equipment been specified?' },
  { category: 'fire_protection', description: 'Will fire containment be adequate where hazardous or reactive chemicals are present?' },
  { category: 'fire_protection', description: 'Has spontaneous heating of leakage into insulation been adequately considered?' },
  { category: 'fire_protection', description: 'Are provisions made for safe handling of flammable or potentially explosive materials?' },
  { category: 'fire_protection', description: 'Are all fire water spray system modifications being designed by qualified personnel?' },
  { category: 'fire_protection', description: 'Have modifications to fire protection systems been reviewed by Safety Department and/or property insurance carrier?' },
  { category: 'fire_protection', description: 'Will vents potentially containing flammables be provided with adequate safety equipment?' },
  { category: 'fire_protection', description: 'Will an adequate detection and response system be provided where a vapor cloud is likely?' },
  { category: 'fire_protection', description: 'Have the risks associated with any ignition source or explosive gas mixture been adequately dealt with?' },
  { category: 'fire_protection', description: 'Has adequate fire safety equipment been specified and located where needed?' },
  { category: 'fire_protection', description: 'Has deluge water overflow from containment systems been determined and reviewed properly?' },
  { category: 'fire_protection', description: 'Is diking, curbing, or drainage adequate to contain spills and contaminated rainwater (RCRA)?' },
  { category: 'personnel_health_industrial_hygiene', description: 'Does the design adequately consider medical, industrial hygiene, ergonomic and GMP factors?' },
  { category: 'personnel_health_industrial_hygiene', description: 'Have adequate provisions been specified for safe handling and sampling of hazardous materials?' },
  { category: 'personnel_health_industrial_hygiene', description: 'Have personnel safety devices (showers, eye baths, fall prevention, breathing air) been specified?' },
  { category: 'personnel_health_industrial_hygiene', description: 'Will all asbestos-containing insulation be removed/repaired per plant requirements?' },
  { category: 'personnel_health_industrial_hygiene', description: 'Will secondary surfaces (grating, slip protection) be provided where freezing or slippery materials are handled?' },
  { category: 'personnel_health_industrial_hygiene', description: 'Has confined space entry been adequately addressed in this design?' },
];
