// PSSR template items — from official Pre-Startup Safety Review Checklist (Appendix VI)
// Shared between pssr.ts route and auto-creation in moc.ts / workflow.ts
export const PSSR_TEMPLATE_ITEMS: { category: string; description: string }[] = [
  // A. Design and Construction
  { category: 'design_and_construction', description: 'Have the concerns from the Design Safety Review been resolved satisfactorily?' },
  { category: 'design_and_construction', description: 'Has the equipment QA turnover procedure been completed?' },
  { category: 'design_and_construction', description: 'Are all applicable Chemical Process Safety Standards Administrative Controls complied with?' },
  { category: 'design_and_construction', description: 'Is construction and equipment in accordance with ISP and other applicable design specifications?' },
  { category: 'design_and_construction', description: 'Has a field inspection been performed?' },
  { category: 'design_and_construction', description: 'Has the job site been properly cleaned up?' },
  { category: 'design_and_construction', description: 'Has adequate surface drainage been provided?' },
  { category: 'design_and_construction', description: 'Are walking/working surfaces level, secured and non-slippery?' },
  { category: 'design_and_construction', description: 'Have emergency access and egress been properly provided for and labeled or marked?' },
  { category: 'design_and_construction', description: 'Are personnel protected from contact with hot (>140°F) surfaces?' },
  { category: 'design_and_construction', description: 'Do walkways and ladders provide safe access to all levels?' },
  { category: 'design_and_construction', description: 'Can elevated work be performed safely?' },
  { category: 'design_and_construction', description: 'Do signs identify work area hazards and provide instruction?' },
  { category: 'design_and_construction', description: 'Is idled equipment properly isolated and identified?' },
  { category: 'design_and_construction', description: 'Is the work area adequately ventilated?' },
  { category: 'design_and_construction', description: 'Is insulation or other equipment free of sharp edges?' },

  // B. Valves and Piping
  { category: 'valves_and_piping', description: 'Are open ended valves of the correct type and plugged or blinded where required?' },
  { category: 'valves_and_piping', description: 'Are hoses and fittings of the approved types?' },
  { category: 'valves_and_piping', description: 'Are check valves installed in the correct orientation and direction?' },
  { category: 'valves_and_piping', description: 'Have tripping hazards been eliminated and adequate clearance provided?' },
  { category: 'valves_and_piping', description: 'Is the piping adequately supported?' },
  { category: 'valves_and_piping', description: 'Has a line-by-line inspection been done?' },
  { category: 'valves_and_piping', description: 'Have nipple lengths been minimized and cantilevered branch connections avoided?' },
  { category: 'valves_and_piping', description: 'Is cathodic protection provided, if specified?' },
  { category: 'valves_and_piping', description: 'Are line expansion provisions installed?' },
  { category: 'valves_and_piping', description: 'Is any piping close to the edge of a pipe rack that could fall off in high wind or during line expansion?' },
  { category: 'valves_and_piping', description: 'Are dead end pipe, pocketed lines, and unused piping branches eliminated?' },
  { category: 'valves_and_piping', description: 'Have valves and flanges subject to fugitive emission monitoring been tagged as required?' },
  { category: 'valves_and_piping', description: 'Is the placement of flanges, unions, drains, etc., adequate for maintenance?' },

  // C. Equipment
  { category: 'equipment', description: 'Has protection been provided against over pressure and vacuum?' },
  { category: 'equipment', description: 'Have guards such as coupling and seal guards been installed on moving equipment?' },
  { category: 'equipment', description: 'Does equipment location provide safe access for operation and maintenance?' },
  { category: 'equipment', description: 'Is equipment adequately supported?' },
  { category: 'equipment', description: 'Are Test and Inspections (T&I) current for reused equipment?' },
  { category: 'equipment', description: 'Was rotation checked?' },
  { category: 'equipment', description: "Is the manufacturer's label visible?" },
  { category: 'equipment', description: 'Is the equipment free from pipe strain?' },

  // D. Instrument and Electrical
  { category: 'instrument_and_electrical', description: 'Was the fail-safe position of valves verified by functional testing?' },
  { category: 'instrument_and_electrical', description: 'Were instruments/analyzers functionally tested?' },
  { category: 'instrument_and_electrical', description: 'Will alarms associated with critical instruments be clearly displayed in the control room?' },
  { category: 'instrument_and_electrical', description: 'Are guards provided to prevent accidental tripping of switches?' },
  { category: 'instrument_and_electrical', description: 'Are indicating lights operational?' },
  { category: 'instrument_and_electrical', description: 'Are conduit fittings sealed?' },
  { category: 'instrument_and_electrical', description: 'Have all junction boxes and electrical switch boxes been properly covered or closed?' },
  { category: 'instrument_and_electrical', description: 'Is electrical heat tracing labeled?' },
  { category: 'instrument_and_electrical', description: 'Are start/stop switches and electrical switchgear labeled?' },
  { category: 'instrument_and_electrical', description: 'Have the correct electrical area classification rules been followed?' },
  { category: 'instrument_and_electrical', description: 'Have the electrical protective devices and safety features been properly calibrated, set, and tested?' },
  { category: 'instrument_and_electrical', description: 'Does the electrical equipment have lockout devices?' },
  { category: 'instrument_and_electrical', description: 'Have the commissioning test results been performed by local plant maintenance?' },
  { category: 'instrument_and_electrical', description: 'Is equipment properly grounded and functionally checked?' },
  { category: 'instrument_and_electrical', description: 'Are ground wires available for tank trucks, tank cars, drums, etc.?' },
  { category: 'instrument_and_electrical', description: 'Is ventilation for batteries/electrical components adequate?' },
  { category: 'instrument_and_electrical', description: 'Is there adequate lighting?' },
  { category: 'instrument_and_electrical', description: 'Are critical instruments, ESD devices, quality instruments, etc., field distinguishable?' },
  { category: 'instrument_and_electrical', description: 'Has adequate local instrumentation been supplied per design specifications for safety and trouble-shooting?' },

  // E. Computer Software and Systems
  { category: 'computer_software_and_systems', description: 'Have all software outputs been tested off-line?' },
  { category: 'computer_software_and_systems', description: 'If the software requires information from other computers, are adequate safeguards provided?' },
  { category: 'computer_software_and_systems', description: 'Have instructions been provided for restarting the computer safely after a shutdown?' },
  { category: 'computer_software_and_systems', description: 'Is sufficient checking of data inputs to software provided to safely operate the facility?' },
  { category: 'computer_software_and_systems', description: 'Has the need for computer training been addressed?' },
  { category: 'computer_software_and_systems', description: 'Is documentation provided for software, including user and technical documentation?' },
  { category: 'computer_software_and_systems', description: 'Are important software functions (critical alarms, ESD devices, process control logic) adequately protected?' },

  // F. Operations
  { category: 'operations', description: 'Are NFPA chemical hazard identification symbols in place?' },
  { category: 'operations', description: 'Can the system be safely started up, shut down or operated on 100% recycle, if applicable?' },
  { category: 'operations', description: 'Are routinely operated valves accessible and easy to operate (gear operators and chain operators provided where necessary)?' },
  { category: 'operations', description: 'Are vents and drains visible and safely located?' },
  { category: 'operations', description: 'Have piping and equipment been installed properly to avoid unnecessary cross-ties which could contribute to contamination, pressure, or temperature problems?' },
  { category: 'operations', description: 'Are sample points properly configured for safe sampling?' },
  { category: 'operations', description: 'Have provisions been made for safe handling of drums and gas cylinders?' },
  { category: 'operations', description: 'Are new lines and equipment adequately labeled, including flow arrows?' },
  { category: 'operations', description: 'Are special procedures for commissioning/decommissioning or first time startup provided?' },
  { category: 'operations', description: 'Have operator and supervisory personnel training sessions been completed and documented?' },
  { category: 'operations', description: 'Are provisions made for technical or supervisory support during initial operation?' },
  { category: 'operations', description: 'Was the change communicated to adjacent units or other affected groups?' },

  // G. Maintenance
  { category: 'maintenance', description: 'Can equipment be cleaned, isolated, locked out, and easily removed?' },
  { category: 'maintenance', description: 'Is equipment and instrumentation reasonably accessible for inspection and maintenance?' },
  { category: 'maintenance', description: 'Is equipment entered on the PM program?' },
  { category: 'maintenance', description: 'Are capacities of lifting equipment, floors, and hoists clearly displayed and visible?' },
  { category: 'maintenance', description: 'Have maintenance personnel whose job task will be affected been trained and training documented?' },
  { category: 'maintenance', description: 'Are necessary spare parts available?' },

  // H. Relief Devices
  { category: 'relief_devices', description: 'Have all relief devices been installed per design?' },
  { category: 'relief_devices', description: 'Relief devices added to checklist?' },
  { category: 'relief_devices', description: 'Are block valves on inlet and outlet of relief devices car sealed open?' },
  { category: 'relief_devices', description: 'Are safety valve discharges directed to a safe location?' },
  { category: 'relief_devices', description: 'Is the inlet or outlet piping at least the same size as the connection on the relief device?' },
  { category: 'relief_devices', description: 'Is the relief device stack adequately braced against any reaction forces?' },
  { category: 'relief_devices', description: 'Are heat exchangers protected on the shell and tube side?' },
  { category: 'relief_devices', description: 'Are weep holes, drains, and/or weather barriers provided in discharge piping of pressure relief devices?' },
  { category: 'relief_devices', description: 'Are relief valves tagged?' },
  { category: 'relief_devices', description: 'Are relief valves installed vertically?' },
  { category: 'relief_devices', description: 'Is there a pressure indicator between rupture disks and relief valves?' },
  { category: 'relief_devices', description: 'Have safety valves been tested and tagged?' },
  { category: 'relief_devices', description: 'Are safety valves under pipe strain?' },

  // I. Fire Protection and Personnel Safety Equipment
  { category: 'fire_protection_and_personnel_safety', description: 'Have inert gas blankets and purges been provided where required?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Are tank legs fire-proofed, where required by OSHA/NFPA standards?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Have sprinkler systems/deluge systems been installed and functionally tested if specified?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Have new fire protection systems and control valves been added to the inspection list?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Have new fire protection systems control valves been car-sealed open?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Have fixed fire protection systems been installed, tested, and labeled?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Has fire protection group approved all changes to fixed fire protection facilities?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Has steam or nitrogen been provided for snuffing fires in safety valve vent headers?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Have Operations and Emergency Response Team personnel been adequately instructed in appropriate support and response procedures?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Have approved fire extinguishers, safety showers, eye baths, fresh air equipment, etc. been installed?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Have flame arrestors been installed as required?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Have Emergency Response procedures been reviewed as necessary?' },
  { category: 'fire_protection_and_personnel_safety', description: 'Has freeze and/or scalding protection been adequately addressed?' },

  // J. Occupational Health / Industrial Hygiene
  { category: 'occupational_health_industrial_hygiene', description: 'Are provisions for monitoring potential high noise areas made?' },
  { category: 'occupational_health_industrial_hygiene', description: 'If regulated chemicals are involved, have the special requirements been observed?' },
  { category: 'occupational_health_industrial_hygiene', description: 'Has a PPE assessment survey been conducted?' },
  { category: 'occupational_health_industrial_hygiene', description: 'Has appropriate PPE been provided, personnel trained and training documented?' },
  { category: 'occupational_health_industrial_hygiene', description: 'Does the system assure minimum personnel exposure to chemicals?' },
  { category: 'occupational_health_industrial_hygiene', description: 'Are provisions made for Industrial Hygiene monitoring during initial or routine operations?' },
  { category: 'occupational_health_industrial_hygiene', description: 'Has exposed asbestos insulation been properly sealed or disposed of?' },

  // K. Environmental Protection
  { category: 'environmental_protection', description: 'Were changes in air emissions, waste, wastewater and storm water flows properly communicated?' },
  { category: 'environmental_protection', description: 'Can hazardous materials from spills or maintenance preparation be safely handled?' },
  { category: 'environmental_protection', description: 'Are environmental permits and inspections/certifications required for operation on file and understood by unit personnel?' },
];
